services:
  - type: web
    name: dropwise-api
    runtime: java
    rootDir: apps/api
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/api-0.0.1-SNAPSHOT.jar --server.port=$PORT
    healthCheckPath: /api/app/health
    envVars:
      - key: AWS_REGION
        sync: false
      - key: AWS_SECRETS_PREFIX
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
